const npcs = [
  {
    index: 0,
    firstname: 'Bron',
    secondname: 'Strongdong',
    race: 'Dwarf',
    trait: 'Loud',
  },
  {
    index: 1,
    firstname: 'Barry',
    secondname: 'Smitherton',
    race: 'Human',
    trait: 'Shy',
  },
  {
    index: 2,
    firstname: 'Erathar',
    secondname: 'Cerebrim',
    race: 'Elf',
    trait: 'Rude',
  },
  {
    index: 3,
    firstname: 'Benbin',
    secondname: 'Quietfoot',
    race: 'Halfling',
    trait: 'Nervous',
  },
  {
    index: 4,
    firstname: 'Daisy',
    secondname: 'Littlecurl',
    race: 'Gnome',
    trait: 'Clumsy',
  },
]

const npcTraits = [
  'Loud',
  'Shy',
  'Clumsy',
  'Rude',
  'Nervous',
  'Cowardly',
  'Bold',
  'Humble',
  'Serious',
  'Stubborn',
  'Gullible',
  'Generous',
  'Selfish',
  'Confident',
  'Respectful',
  'Considerate',
  'Independent',
  'Carefree',
  'Intelligent',
  'Mischievous',
  'Hardworking',
  'Charming',
  'Lazy',
  'Responsible',
  'Helpful',
  'Cautious',
  'Polite',
  'Conceited',
  'Demanding',
  'Bossy',
  'Proud',
  'Gentle',
  'Mysterious',
  'Eager',
  'Hopeful',
  'Lucky',
  'Cooperative',
  'Ambitious',
  'Curious',
  'Mature',
  'Calm',
  'Energetic',
  'Calm',
  'Strict',
  'Annoyed',
  'Foolish',
  'Grumpy',
  'Miserable',
  'Sly',
  'Thoughtful',
  'Tolerant',
  'Weak',
  'Wise',
  'Jealous',
  'Lonely',
]

const dwarfNamesMale = [
  'Adrik',
  'Alberich',
  'Baern',
  'Barendd',
  'Beloril',
  'Brottor',
  'Dain',
  'Dalgal',
  'Darrak',
  'Delg',
  'Duergath',
  'Dworic',
  'Eberk',
  'Einkil',
  'Elaim',
  'Erias',
  'Fallond',
  'Fargrim',
  'Gardain',
  'Gilthur',
  'Gimgen',
  'Gimurt',
  'Harbek',
  'Kildrak',
  'Kilvar',
  'Morgran',
  'Morkral',
  'Nalral',
  'Nordak',
  'Nuraval',
  'Oloric',
  'Olunt',
  'Orsik',
  'Oskar',
  'Rangrim',
  'Reirak',
  'Rurik',
  'Taklinn',
  'Thoradin',
  'Thorin',
  'Thradal',
  'Tordek',
  'Traubon',
  'Travok',
  'Ulfgar',
  'Uraim',
  'Veit',
  'Vonbin',
  'Vondal',
  'Whurbin',
]

const dwarfNamesFemale = [
  'Anbera',
  'Artin',
  'Audhild',
  'Balifra',
  'Barbena',
  'Bardryn',
  'Bolhild',
  'Dagnal',
  'Dariff',
  'Delre',
  'Diesa',
  'Eldeth',
  'Eridred',
  'Falkrunn',
  'Fallthra',
  'Finellen',
  'Gillydd',
  'Gunnloda',
  'Gurdis',
  'Helgret',
  'Helja',
  'Hlin',
  'Ilde',
  'Jarana',
  'Kathra',
  'Kilia',
  'Kristryd',
  'Liftrasa',
  'Marastyr',
  'Mardred',
  'Morana',
  'Nalaed',
  'Nora',
  'Nurkara',
  'Oriff',
  'Ovina',
  'Riswynn',
  'Sannl',
  'Therlin',
  'Thodris',
  'Torbera',
  'Tordrid',
  'Torgga',
  'Urshar',
  'Valida',
  'Vistra',
  'Vonana',
  'Werydd',
  'Whurdred',
  'Yurgunn',
]

const dwarfNamesAll = dwarfNamesMale.concat(dwarfNamesFemale)

const dwarfClan = [
  'Aranore',
  'Balderk',
  'Battlehammer',
  'Bigtoe',
  'Bloodkith',
  'Bofdann',
  'Brawnanvil',
  'Brazzik',
  'Broodfist',
  'Burrowfound',
  'Caebrek',
  'Daerdahk',
  'Dankil',
  'Daraln',
  'Deepdelver',
  'Durthane',
  'Eversharp',
  'Fallack',
  'Fireforge',
  'Foamtankard',
  'Frostbeard',
  'Glanhig',
  'Goblinbane',
  'Goldfinder',
  'Gorunn',
  'Graybeard',
  'Hammerstone',
  'Helcral',
  'Holderhek',
  'Ironfist',
  'Loderr',
  'Lutgehr',
  'Morigak',
  'Orcfoe',
  'Rakankrak',
  'Ruby-Eye',
  'Rumnaheim',
  'Silveraxe',
  'Silverstone',
  'Steelfist',
  'Stoutale',
  'Strakeln',
  'Strongheart',
  'Thrahak',
  'Torevir',
  'Torunn',
  'Trollbleeder',
  'Trueanvil',
  'Trueblood',
  'Ungart',
]

const dragonbornNamesFemale = [
  'Akra',
  'Aasathra',
  'Antrara',
  'Arava',
  'Biri',
  'Blendaeth',
  'Burana',
  'Chassath',
  'Daar',
  'Dentratha',
  'Doudra',
  'Driindar',
  'Eggren',
  'Farideh',
  'Findex',
  'Furrele',
  'Gesrethe',
  'Gilkass',
  'Harann',
  'Havilar',
  'Hethress',
  'Hillanot',
  'Jaxi',
  'Jezean',
  'Jheri',
  'Kadana',
  'Kava',
  'Korinn',
  'Megren',
  'Mijira',
  'Mishann',
  'Nala',
  'Nuthra',
  'Perra',
  'Pogranix',
  'Pyxrin',
  'Quespa',
  'Raiann',
  'Rezena',
  'Ruloth',
  'Saphara',
  'Savaran',
  'Sora',
  'Surina',
  'Synthrin',
  'Tatyan',
  'Thava',
  'Uadjit',
  'Vezera',
  'Zykroff',
]

const dragonbornNamesMale = [
  'Adrex',
  'Arjhan',
  'Azzakh',
  'Balasar',
  'Baradad',
  'Bharash',
  'Bidreked',
  'Dadalan',
  'Dazzazn',
  'Direcris',
  'Donaar',
  'Fax',
  'Gargax',
  'Ghesh',
  'Gorbundus',
  'Greethen',
  'Heskan',
  'Hirrathak',
  'Ildrex',
  'Kaladan',
  'Kerkad',
  'Kiirith',
  'Kriv',
  'Maagog',
  'Medrash',
  'Mehen',
  'Mozikth',
  'Mreksh',
  'Mugrunden',
  'Nadarr',
  'Nithther',
  'Norkruuth',
  'Nykkan',
  'Pandjed',
  'Patrin',
  'Pijjirik',
  'Quarethon',
  'Rathkran',
  'Rhogar',
  'Rivaan',
  'Sethrekar',
  'Shamash',
  'Shedinn',
  'Srorthen',
  'Tarhun',
  'Torinn',
  'Trynnicus',
  'Valorean',
  'Vrondiss',
  'Zedaar',
]

const dragonbornNamesAll = dragonbornNamesMale.concat(dragonbornNamesMale)

const dragonbornClan = [
  'Akambherylliax',
  'Argenthrixus',
  'Baharoosh',
  'Beryntolthropal',
  'Bhenkumbyrznaax',
  'Caavylteradyn',
  'Chumbyxirinnish',
  'Clethtinthiallor',
  'Daardendrian',
  'Delmirev',
  'Dhyrktelonis',
  'Ebynichtomonis',
  'Esstyrlynn',
  'Fharngnarthnost',
  'Ghaallixirn',
  'Grrrmmballhyst',
  'Gygazzylyshrift',
  'Hashphronyxadyn',
  'Hshhsstoroth',
  'Imbixtellrhyst',
  'Jerynomonis',
  'Jharthraxyn',
  'Kerrhylon',
  'Kimbatuul',
  'Lhamboldennish',
  'Linxakasendalor',
  'Mohradyllion',
  'Mystan',
  'Nemmonis',
  'Norixius',
  'Ophinshtalajiir',
  'Orexijandilin',
  'Pfaphnyrennish',
  'Phrahdrandon',
  'Pyraxtallinost',
  'Qyxpahrgh',
  'Raghthroknaar',
  'Shestendeliath',
  'Skaarzborroosh',
  'Sumnarghthrysh',
  'Tiammanthyllish',
  'Turnuroth',
  'Umbyrphrael',
  'Vangdondalor',
  'Verthisathurgiesh',
  'Wivvyrholdalphiax',
  'Wystongjiir',
  'Xephyrbahnor',
  'Yarjerit',
  'Zzzxaaxthroth',
]

const dragonbornColor = ['Black', 'Blue', 'Brass', 'Bronze', 'Copper', 'Gold', 'Green', 'Red', 'Silver', 'White']
